### ISSUE TITLE
Add C++ example

### ISSUE THREAD

**Issue by kelteseth** [amd/RyzenAI-SW#10]
Hi, I would like to see a complete C++/Qt example featuring the following:

- Setup project with modern CMake and vcpkg. What do I need to install via vcpkg. When [browsing vcpkg](https://vcpkg.link/search#q=onnx) for onnx, there are several versions one can install. Do I need to install tensorflow as well, or is onnx enough?
- Loading of the model using c++
- Things needed for deployment like what drivers do my user need, what dlls do I need to copy where. There is already a pyhon example, and my guess would be that the cpp version is similar https://ryzenai.docs.amd.com/en/latest/getstartex.html#deploy-the-model-on-the-ryzen-ai-ipu

**Comment by kelteseth** [comment]
Similar to https://onnxruntime.ai/docs/execution-providers/Vitis-AI-ExecutionProvider.html but as a downloadable example

**Comment by savitha-srinivasan** [comment]
We are working on this, we should have a C++ example in the next release.

**Comment by kelteseth** [comment]
Huh, where are the examples?

**Comment by andyluo7** [comment]
@kelteseth , https://github.com/amd/RyzenAI-SW/tree/main/example/yolov8 is a C++ example which is a little complex than the get-started Resnet50 example. We plan to add C++ example for Resnet50 in the next release.
