### ISSUE TITLE
Opt Transformer Example issues: pybind11, numpy version, %1 ist not a valid Win32 application

### ISSUE THREAD

**Issue by ksjogo** [amd/RyzenAI-SW#104]
I am following the tutorial to run the opt locally, two issues I ran into before (when just following the tutorial):
* pybind11 is not installed and wheeling RyzenAI fails. I did do a  `conda install -c conda-forge pybind11` which seems to have worked
* Ryzen AI did give a `np.float_was` removed in the NumPy 2.0 release. Usenp.float64 instead.` as it somehow was picking up numpy 2 from the conda context. Did do a `pip uninstall numpy
pip install numpy==1.26.4` to fix that.

Now I am stuck there though:

```
(ryzenai-transformers) C:\Users\jogo\dev\RyzenAI-SW\example\transformers\models\opt>python run_awq.py --task quantize --model_name opt-1.3b
1.26.4
Traceback (most recent call last):
  File "C:\Users\jogo\dev\RyzenAI-SW\example\transformers\models\opt\run_awq.py", line 18, in <module>
    import qlinear
  File "C:\Users\jogo\dev\RyzenAI-SW\example\transformers\ops\python\qlinear.py", line 21, in <module>
    import RyzenAI
ImportError: DLL load failed while importing RyzenAI: %1 is not a valid Win32 application.

(ryzenai-transformers) C:\Users\jogo\dev\RyzenAI-SW\example\transformers\models\opt>
```

**Comment by poganesh** [comment]
Hi @ksjogo, 

Could you please check if your python environment is 64-bit? Here's how you can do it:

- Open a python interpreter and run the following code:

`import platform`
`print(platform.architecture())`

Additionally, could you please provide the following system information to help diagnose the issue:
- OS name and version
- System Type (32-bit or 64-bit)
- Processor

**Comment by ksjogo** [comment]
Hi, that returns:
```
('64bit', 'WindowsPE')
```
It's Windows 11 23H2. 
CPU: AMD Ryzen 9 7940HS

**Comment by uday610** [comment]
As the new 1.2 flow is released. This flow is obsoleted. Closing
