### ISSUE TITLE
opt-onnx import issue

### ISSUE THREAD

**Issue by ksjogo** [amd/RyzenAI-SW#105]
Following the onnx opt tutorial I run into trouble with a version mismatch of huggingface-hub and the transformers package:
```
 File "C:\Users\jogo\.conda\envs\ryzenai-transformers\lib\site-packages\transformers\utils\import_utils.py", line 1272, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\jogo\.conda\envs\ryzenai-transformers\lib\site-packages\transformers\utils\import_utils.py", line 1284, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (C:\Users\jogo\.conda\envs\ryzenai-transformers\lib\site-packages\huggingface_hub\__init__.py)
```

**Comment by shivani-athavale** [comment]
Hi @ksjogo,

I reproduced the error on my side and observed that **pip install --upgrade huggingface_hub** will help resolve this issue.

**Comment by madcrow99** [comment]
Thanks! This does fix the issue but I got the warning beow.
<img width="590" alt="image" src="https://github.com/user-attachments/assets/55cdf14a-4473-4485-aa7c-0f06a863c960">
That being said, the OPT1.3B pytorch example is running well.

**Comment by uday610** [comment]
closing as the model is running well
