### ISSUE TITLE
Would add some document to explain how to install RyzenAI SW to existed docker container，or how to install on linunx

### ISSUE THREAD

**Issue by joebnb** [amd/RyzenAI-SW#106]
TLDR

there have no documents to tell how to  install  ryzen ai to use on linux, i want use amd npu to accelerate ai computing,but did konw how to make it works

**Comment by joebnb** [comment]
https://hub.docker.com/r/intel/intel-optimized-pytorch seems intel take advantage alot

**Comment by uday610** [comment]
duplicate of issue #2

**Comment by uday610** [comment]
closed as duplicate
