### ISSUE TITLE
how to run llama2 run_awq.py without preparing layers each run

### ISSUE THREAD

**Issue by madcrow99** [amd/RyzenAI-SW#109]
Is it possible to run the run_awq.py in the llama2 folder without having to prepare the weights each run? It is quite time consuming. I am running this on the aie for ryzenai. The model runs well with no issues but ideally, it would load more quickly.

    if args.awq != "none":
        for n, m in model.named_modules():
            if isinstance(m, qlinear.QLinearPerGrp):
                print(f"Preparing weights of layer : {n}")
                m.device = "aie"
                m.quantize_weights()

**Comment by shivani-athavale** [comment]
Hello @madcrow99,

As of now, we do not have the ability to save the model checkpoint after this 'quantize_weights' step.

We can only save the model checkpoint after using '--task quantize'.

Also, we have updated the LLM flow recently, you might have already noticed.
