### ISSUE TITLE
NPU Usage is always keeps at 0% when running Hello World Example

### ISSUE THREAD

**Issue by mattchai** [amd/RyzenAI-SW#112]
I found NPU Usage is always keeps at 0% when running Hello World Example, is there any other example that can be run for checking NPU usage?

**Comment by uday610** [comment]
The example is really very short, and the load on the NPU is very small. You can run inference in a loop (adding a loop for the `session.run()` command) to see NPU activities.

**Comment by mattchai** [comment]
Hi， even I added a loop for the npu_results = aie_session.run(None, {'input': input_data}), but NPU usage is still keeps at 0%, I think it caused by the example small loading on the NPU.

It will be appreciate if you can provide an example which has a big loading on the NPU, thanks.

**Comment by shivani-athavale** [comment]
Hi @mattchai, can you try the https://github.com/amd/RyzenAI-SW/tree/main/tutorial/getting_started_resnet example and run the inference in a loop (add a loop for the session.run() command) to see NPU activities.

**Comment by mattchai** [comment]
Hi @shivani-athavale, the NPU usage is around 74%~77% after running getting_started_resnet example in a loop, is there any other example that NPU usage can reach to 90% or above 90%. this ticket can be closed if no such example, thanks a lot.

**Comment by uday610** [comment]
The NPU usage you see in Task Manager is not related to the amount of space utilized on the NPU. Therefore, 75% usage does not mean that 75% of the NPU is filled and 25% is empty. In this context, the percentage only denotes the command execution time. It represents OS-related data, measuring the percentage of time the command is executing on the NPU relative to the total time.

**Comment by mattchai** [comment]
Hi @uday610， thanks for your explanation， could you please help to clarify below questions:
1. If CPU usage in Task Manager is 100% but NPU usage is 75% when execute the same task, does it mean NPU is 25% faster than CPU.
2. Is there any other tool that can check "the amount of space utilized on the NPU".

**Comment by uday610** [comment]
No, we cannot draw such a conclusion. It is just the way OS reports, time spent in command submitted vs time spent in command executed..

I don't think you can do anything checking NPU space... Because everything is scheduled automatically, and runtime accommodates multiple inference sessions by itself. I don't think the user has any reason to check NPU space. 

I will close this ticket as your questions are answered.
