### ISSUE TITLE
Onnx Benchmark error

### ISSUE THREAD

**Issue by mattchai** [amd/RyzenAI-SW#113]
I got below error when running Onnx Benchmark with python performance_benchmark.py -m .\models\resnet50\resnet50_fp32.onnx -n 100 -d CPU scripts.

![benchmark error](https://github.com/user-attachments/assets/13b00314-cafc-4265-8524-e577771ed454)

**Comment by cyndwith** [comment]
Thanks for reporting the issue, we are able to reproduce it. We will update onnx-benchmark example with a fix in some time.

**Comment by cyndwith** [comment]
@mattchai Latest changes in the onnx-benchmark should fix this issue.

**Comment by mattchai** [comment]
@cyndwith, yes, this issue can be fixed by the latest changes, please help to close this issue.
