### ISSUE TITLE
ai analyzer warning of AIE metadata JSON file

### ISSUE THREAD

**Issue by roycezjq** [amd/RyzenAI-SW#116]
When I profiled a model following the instructions in this doc(https://ryzenai.docs.amd.com/en/latest/ai_analyzer.html), I got the following warning:

```
XRT build version: 2.18.0
Build hash: 54b1a0335ef517415d17206d30365cf4a2c380d0
Build date: 2024-07-26 18:39:44
Git branch: HEAD
PID: 417568
UID: 0
[Mon Aug 26 09:37:31 2024 GMT]
EXE:
[XRT] WARNING: The AIE metadata JSON file is required in the same directory as the run directory to run AIE Profile.
[XRT] WARNING: The AIE metadata JSON file is required in the same directory as the run directory to run AIE Profile.
[XRT] WARNING: AIE metadata read failed on client!
```

And I can't get the profiling result.

What is AIE metadata JSON file? And where can I find this file? Thanks

**Comment by savitha-srinivasan** [comment]
Hi @roycezjq , 

The profiling artifacts should have been generated in your current directory despite the warnings. Did you [launch](https://ryzenai.docs.amd.com/en/latest/ai_analyzer.html#launching-ai-analyzer) the analyzer after generating the artifacts?

**Comment by roycezjq** [comment]
> Hi @roycezjq ,
> 
> The profiling artifacts should have been generated in your current directory despite the warnings. Did you [launch](https://ryzenai.docs.amd.com/en/latest/ai_analyzer.html#launching-ai-analyzer) the analyzer after generating the artifacts?

Thanks for the quick reply. I got some files in the cache folder:
![image](https://github.com/user-attachments/assets/04405aa7-7caf-4109-a872-70bf67c18f91)
And the aianalyzer running like this:
![image](https://github.com/user-attachments/assets/092a6ca7-0aec-4014-aa14-08b70ac26ae8)
There're graph and summary, but not latency info.

**Comment by roycezjq** [comment]
> Hi @roycezjq ,
> 
> The profiling artifacts should have been generated in your current directory despite the warnings. Did you [launch](https://ryzenai.docs.amd.com/en/latest/ai_analyzer.html#launching-ai-analyzer) the analyzer after generating the artifacts?

I think I specified the wrong folder for aianalyzer tool. I got the latency info now. Thanks a lot for the help.
