### ISSUE TITLE
Selecting the 5x4.xclbin IPU binary

### ISSUE THREAD

**Issue by blurSong** [amd/RyzenAI-SW#13]
I think there is a miss. The cmd of IPU Binary selection https://ryzenai.docs.amd.com/en/latest/runtime_setup.html#runtime-setup
`set XLNX_TARGET_NAME="AMD_AIE2_5x4_Overlay"`
should be:
`set XLNX_TARGET_NAME=AMD_AIE2_5x4_Overlay`

**Comment by uday610** [comment]
Thanks for reporting, This if fixed now
