### ISSUE TITLE
ryzenai_1.2.0.msi installation fail

### ISSUE THREAD

**Issue by xeasonx** [amd/RyzenAI-SW#130]
Processor: AMD Ryzen AI 9 365 w/ Radeon 880M
System: Windows 11 Version24H2 (OS Build 26100.2033)
Installer: ryzen-ai-1.2.0-20240726.msi

During the install process, a CMD window prompt.
![image](https://github.com/user-attachments/assets/f28b10db-7dfa-4e14-99f1-914b6942a9a2)
After a while, the CMD window closed, and show and error.
![image](https://github.com/user-attachments/assets/772fe0f3-d491-4ba5-ae2c-ddd6757a3817)
The installation failed. The error log shows this:
```
D:\softwares\miniconda3\Lib\argparse.py:2006: FutureWarning: `remote_definition` is deprecated and will be removed in 25.9. Use `conda env create --file=URL` instead.
  action(self, namespace, argument_values, option_string)
Pip subprocess error:
'chcp' \ufffd\ufffd\ufffd\ufffd\ufffd\u06b2\ufffd\ufffd\ufffd\ufffd\u2cbf\ufffd\ufffd\ufffd\ue8ec\u04b2\ufffd\ufffd\ufffd\u01ff\ufffd\ufffd\ufffd\ufffdе\u0133\ufffd\ufffd\ufffd
\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u013c\ufffd\ufffd\ufffd
'chcp' \ufffd\ufffd\ufffd\ufffd\ufffd\u06b2\ufffd\ufffd\ufffd\ufffd\u2cbf\ufffd\ufffd\ufffd\ue8ec\u04b2\ufffd\ufffd\ufffd\u01ff\ufffd\ufffd\ufffd\ufffdе\u0133\ufffd\ufffd\ufffd
\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u013c\ufffd\ufffd\ufffd
'chcp' \ufffd\ufffd\ufffd\ufffd\ufffd\u06b2\ufffd\ufffd\ufffd\ufffd\u2cbf\ufffd\ufffd\ufffd\ue8ec\u04b2\ufffd\ufffd\ufffd\u01ff\ufffd\ufffd\ufffd\ufffdе\u0133\ufffd\ufffd\ufffd
\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u013c\ufffd\ufffd\ufffd


CondaEnvException: Pip failed
```

**Comment by wybaby** [comment]
Same issue.
A error occured when the setup wizard tried to create ryzen environment and the log file "C:\Temp\ryzenai_1.2.0_error_log.txt" showed the following content:
```
D:\anaconda3\Lib\argparse.py:2006: FutureWarning: `remote_definition` is deprecated and will be removed in 25.9. Use `conda env create --file=URL` instead.
  action(self, namespace, argument_values, option_string)

EnvironmentFileNotFound: 'C:\Windows\Installer\SFXCAD4CC70A2004F90AA458B478F69FFC0DE\env.yaml' file not found
```



System Enviroment:
```
Ryzen 9 PRO 7940HS
NPU Drivers is installed successfully
Windows 11 24H2 26100.2161 
Visual Studio 2022 
cmake v3.31.0-rc2
Anaconda 24.9.2
```

**Comment by cyndwith** [comment]
Make sure to use the MSI installer to uninstall the existing installation of RyzenAI-SW. 
Remove the existing conda environment manually using "conda remove --name ryzen-ai-1.2.0 --all --yes". 

Let us know if this resolves the issue.

**Comment by wybaby** [comment]
> Make sure to use the MSI installer to uninstall the existing installation of RyzenAI-SW. Remove the existing conda environment manually using "conda remove --name ryzen-ai-1.2.0 --all --yes".
> 
> Let us know if this resolves the issue.

Thanks for your replay, unfortunately it does not work.

**Comment by xeasonx** [comment]
I think the problem maybe that the installer can't execute msbuild tool, because it is not in system PATH environment. I solve the issue by doing these.
1. After install Visual Studio 2022, add msbuild tool to SYSTEM PATH, for example: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64.
2. Also make sure that `C:\Windows\System32` and `C:\Windows\SysWOW64` is in SYSTEM PATH too.
3. Remove conda environment created by the installer previous, `conda remove --name ryzen-ai-1.2.0 --all --yes`.
4. Open a terminal with administration privilege, execute `ryzen-ai-1.2.0-20240726.msi`. DO NOT change the default installation path, I encountered the same `env.yml` not found problem when I tried to install it on other path.
5. In step 3, if you still got `env.yml` not found error, go to step 3 and install again, it is just another tricky point.
After that, I ran the quicktest.py and test pass.
![image](https://github.com/user-attachments/assets/8afccc70-3b8d-4239-8625-73be1c2e6d6b)

**Comment by wybaby** [comment]
> I think the problem maybe that the installer can't execute msbuild tool, because it is not in system PATH environment. I solve the issue by doing these.
> 
> 1. After install Visual Studio 2022, add msbuild tool to SYSTEM PATH, for example: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64.
> 2. Also make sure that `C:\Windows\System32` and `C:\Windows\SysWOW64` is in SYSTEM PATH too.
> 3. Remove conda environment created by the installer previous, `conda remove --name ryzen-ai-1.2.0 --all --yes`.
> 4. Open a terminal with administration privilege, execute `ryzen-ai-1.2.0-20240726.msi`. DO NOT change the default installation path, I encountered the same `env.yml` not found problem when I tried to install it on other path.
> 5. In step 3, if you still got `env.yml` not found error, go to step 3 and install again, it is just another tricky point.
>    After that, I ran the quicktest.py and test pass.
>    ![image](https://private-user-images.githubusercontent.com/19488467/383390870-8afccc70-3b8d-4239-8625-73be1c2e6d6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODMzNDAsIm5iZiI6MTczMDg4MzA0MCwicGF0aCI6Ii8xOTQ4ODQ2Ny8zODMzOTA4NzAtOGFmY2NjNzAtM2I4ZC00MjM5LTg2MjUtNzNiZTFjMmU2ZDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA4NTA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMGY1NzI3OWViMWYyNmVmOWIxNzllYjI1N2I4YTE0NGVlOTAzZjI0NTU2YjJjM2NhZGI3NGE0MGU3N2JmNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qG7ljSjBLozsMMoUZLEmLePbQ4rQ2JxbSp0eA2WpAlQ)

It works! Thanks a lot.

**Comment by wybaby** [comment]
> I think the problem maybe that the installer can't execute msbuild tool, because it is not in system PATH environment. I solve the issue by doing these.
> 
> 1. After install Visual Studio 2022, add msbuild tool to SYSTEM PATH, for example: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64.
> 2. Also make sure that `C:\Windows\System32` and `C:\Windows\SysWOW64` is in SYSTEM PATH too.
> 3. Remove conda environment created by the installer previous, `conda remove --name ryzen-ai-1.2.0 --all --yes`.
> 4. Open a terminal with administration privilege, execute `ryzen-ai-1.2.0-20240726.msi`. DO NOT change the default installation path, I encountered the same `env.yml` not found problem when I tried to install it on other path.
> 5. In step 3, if you still got `env.yml` not found error, go to step 3 and install again, it is just another tricky point.
>    After that, I ran the quicktest.py and test pass.
>    ![image](https://private-user-images.githubusercontent.com/19488467/383390870-8afccc70-3b8d-4239-8625-73be1c2e6d6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODMzNDAsIm5iZiI6MTczMDg4MzA0MCwicGF0aCI6Ii8xOTQ4ODQ2Ny8zODMzOTA4NzAtOGFmY2NjNzAtM2I4ZC00MjM5LTg2MjUtNzNiZTFjMmU2ZDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA4NTA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMGY1NzI3OWViMWYyNmVmOWIxNzllYjI1N2I4YTE0NGVlOTAzZjI0NTU2YjJjM2NhZGI3NGE0MGU3N2JmNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qG7ljSjBLozsMMoUZLEmLePbQ4rQ2JxbSp0eA2WpAlQ)

It works! Thanks a lot!

**Comment by dorvan** [comment]
on AMD RyzenAI 1.4.0 the problem reappears again on both environment setups, with the correct prerequisites.

**Comment by iz0eyj** [comment]
I really don't understand, they pretend to be a serious company, and maybe in part they are... but then they make similar mistakes causing problems for users and no one who takes the trouble to assist those who need help.
