### ISSUE TITLE
Enable NPU power monitor on Ryzen 5 7640U

### ISSUE THREAD

**Issue by jena1-usr** [amd/RyzenAI-SW#142]
I need to enable power monitor on Ryzen 5 7640U with NPU. During NPU task I execute the xrt-smi examine --report platform  cmd, but it returns no power value: 

---------------------
[00c2:00:01.1] : NPU
---------------------
Platform
  Name                   : NPU
  Power Mode             : Turbo

Power                    : N/A

Does this NPU-Type support power monitoring? On the other site the npu validate check works properly by typing xrt-smi validate --run all, so xrt should be fine: 

Validate Device           : [00c2:00:01.1]
    Platform              : NPU
    Power Mode            : Performance
-------------------------------------------------------------------------------
Test 1 [00c2:00:01.1]     : latency
    Details               : Average latency: 110.0 us
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 2 [00c2:00:01.1]     : throughput
    Details               : Average throughput: 23385.2 ops
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 3 [00c2:00:01.1]     : cmd-chain-latency
    Details               : Average latency: 27.7 us
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 4 [00c2:00:01.1]     : cmd-chain-throughput
    Details               : Average throughput: 35808.7 ops
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 5 [00c2:00:01.1]     : df-bw
    Details               : Average bandwidth per shim DMA: 23.0 GB/s
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 6 [00c2:00:01.1]     : tct-one-col
    Details               : Average TCT throughput: 192346.5 TCT/s
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 7 [00c2:00:01.1]     : tct-all-col
    Details               : Average TCT throughput: 419662.0 TCT/s
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 8 [00c2:00:01.1]     : aie-reconfig-overhead
    Details               : Array reconfiguration overhead: 9.7 ms
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 9 [00c2:00:01.1]     : spatial-sharing-overhead
    Details               : Overhead: 5752.9 ms
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 10 [00c2:00:01.1]    : temporal-sharing-overhead
    Details               : Overhead: '11426.6' ms
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Validation completed. Please run the command '--verbose' option for more details

Does anyone have an idea about the missing Power Value?

**Comment by ThomasXilinx** [comment]
@jena1-usr, this is the expected behavior. Power is only reported for the STX family of devices. Power reporting is not available for PHX or HPT families. We will update the documentation accordingly.
