### ISSUE TITLE
Failed to create GE handle: Error: No compatible xclbin file found

### ISSUE THREAD

**Issue by basp-2024** [amd/RyzenAI-SW#146]
I encountered an issue while running the quicktest . 

The environment variables are set as follows:
```
XLNX_VART_FIRMWARE= C:\Program Files\RyzenAI\1.3.0\voe-4.0-win_amd64\xclbins\phoenix\1x4.xclbin
NUM_OF_DPU_RUNNERS= 1
XLNX_TARGET_NAME= AMD_AIE2_Nx4_Overlay
```
The model compilation process completes successfully, and I get the following logs:

```
[vitisai_compile_model.cpp:1046] Vitis AI EP Load ONNX Model Success
[vitisai_compile_model.cpp:1051]          input : [-1x3x32x32]
[vitisai_compile_model.cpp:1061]          output : [-1x10]
[Vitis AI EP] No. of Operators :   CPU     2    NPU   398 
[Vitis AI EP] No. of Subgraphs :   CPU     1    NPU     1 Actually running on NPU     1
```

However, I encounter the following warning and error during initialization:

```
[W:onnxruntime:, session_state.cc:1166 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf

[W:onnxruntime:, session_state.cc:1168 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.

[custom_op.cpp:552] -- Error: Failed to create GE handle: Error: No compatible xclbin file found

Failed to create an InferenceSession: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: private: static void __cdecl google::protobuf::FieldDescriptor::TypeOnceInit(class google::protobuf::FieldDescriptor const * __ptr64)
public: virtual unsigned char * __ptr64 __cdecl google::protobuf::internal::ZeroFieldsBase::_InternalSerialize(unsigned char * __ptr64,class google::protobuf::io::EpsCopyOutputStream * __ptr64)const __ptr64
__CxxFrameHandler4
(unknown)
RtlCaptureContext2
public: void __cdecl vaip_core::DpuSubgraphEntryProto::unsafe_arena_set_allocated_try_fuse(class vaip_core::TryFuseProto * __ptr64) __ptr64
public: void __cdecl vaip_core::DpuSubgraphEntryProto::unsafe_arena_set_allocated_try_fuse(class vaip_core::TryFuseProto * __ptr64) __ptr64
(unknown)
PyInit_onnxruntime_pybind11_state
PyInit_onnxruntime_pybind11_state
PyInit_onnxruntime_pybind11_state
PyInit_onnxruntime_pybind11_state
PyInit_onnxruntime_pybind11_state
PyInit_onnxruntime_pybind11_state
PyInit_onnxruntime_pybind11_state
PyInit_onnxruntime_pybind11_state
PyInit_onnxruntime_pybind11_state
PyInit_onnxruntime_pybind11_state
public: void __cdecl pybind11::error_already_set::discard_as_unraisable(class pybind11::object) __ptr64
PyCFunction_GetFlags
_PyObject_MakeTpCall
PyMethod_Self
_PyOS_URandomNonblock
PyEval_GetFuncDesc
_PyEval_EvalFrameDefault
_PyEval_EvalFrameDefault
_PyFunction_Vectorcall
_PyOS_URandomNonblock
PyEval_GetFuncDesc
_PyEval_EvalFrameDefault
_PyEval_EvalFrameDefault
_PyFunction_Vectorcall

```

**Steps Taken:**

- Followed the instructions specified in [docs](https://ryzenai.docs.amd.com/en/latest/inst.html) 
- Set the environment variables as required.
- Verified that the xclbin file exists at the specified location (C:\Program Files\RyzenAI\1.3.0\voe-4.0-win_amd64\xclbins\phoenix\1x4.xclbin).
- Attempted run the [quicktest](https://ryzenai.docs.amd.com/en/latest/inst.html#test-the-installation) model using the Vitis AI framework.

**What I've Tried:**

- Rechecking the path for the xclbin file to ensure it is correct.
- Ensuring that all necessary dependencies for Vitis AI and ONNXRuntime are installed.

**Expected Behavior:**
- The model should be loaded and executed successfully without the "No compatible xclbin file found" error.

```
[Vitis AI EP] No. of Operators :   CPU     2    NPU   398
[Vitis AI EP] No. of Subgraphs :   NPU     1 Actually running on NPU     1
...
Test Passed
...
```

**System Info**

**Processor:**	AMD Ryzen 9 7940HS w/ Radeon 780M Graphics        4.00 GHz
**Installed RAM:**	32.0 GB (29.8 GB usable)
**System type:**	64-bit operating system, x64-based processor
**Edition:**	Windows 11 Pro

I am able to run [Hello world](https://github.com/amd/RyzenAI-SW/blob/main/tutorial/hello_world/hello_world.py) and [Resnet](https://github.com/amd/RyzenAI-SW/tree/main/tutorial/getting_started_resnet) examples without any errors.

Please provide suggestions on how to resolve the issue, especially regarding the xclbin file compatibility or any steps to debug this error further.

**Comment by heman-CL** [comment]
Hi, 

I'm not sure if it works. 

I can run 1.2.0 on my Ryzen AI 9 HX 890M graphics, which is strix. 
However, I've faced the same error while using 1.3.0 

I've tried to search "modelcachekey_quicktest" and then find there's a folder which restored cache files. 
After manually deleting that folder, I can run quicktest.py with 1.3.0 

Hope this works

**Comment by basp-2024** [comment]
Hi @heman-CL,

Worked for me by deleting modelcachekey_quicktest

Thanks

**Comment by Pimeq** [comment]
hi lads, sorry for asking but where can I find that folder as well? My windows search is a bit iffy and it sometimes works bad and sometimes worse. Thanks in advance

**Comment by ThomasXilinx** [comment]
The default cache folder is in C:\temp\{user}\vaip\.cache. See the docs for this:
https://ryzenai.docs.amd.com/en/latest/modelrun.html#vitis-ai-execution-provider-options

On this page, you will also see how to change the default location of the changem, change the default name, and optionally disable the usage of the cache.

See this other section of the documentation for recommendations related to cache management:
https://ryzenai.docs.amd.com/en/latest/app_development.html#cache-management
