### ISSUE TITLE
DPU disabled - is it on purpose?

### ISSUE THREAD

**Issue by giovanniguasti** [amd/RyzenAI-SW#19]
in the quantization tutorial the option 
enable_dpu=True
is missing

I do not know if this is wanted or not, but in this way the quantized model will never be assigned to DPU

    vai_q_onnx.quantize_static(
        input_model_path,
        output_model_path,
        data_reader,
        quant_format=QuantFormat.QDQ,
        calibrate_method=vai_q_onnx.PowerOfTwoMethod.MinMSE,
        activation_type=QuantType.QUInt8,
        **enable_dpu=True,**
        weight_type=QuantType.QInt8,
        extra_options={'ActivationSymmetric': True}
    )

**Comment by uday610** [comment]
Hi @giovanniguasti ,
In the current version of the tutorial I do see the ``enable_dpu=True``, 
https://github.com/amd/RyzenAI-SW/blob/main/tutorial/RyzenAI_quant_tutorial/onnx_example/onnx_model_ptq/quantize_onnx_model_ipu.py#L125 

Please review and close this ticket as this seems addressed now

**Comment by uday610** [comment]
closed
