### ISSUE TITLE
Exception during initialization: Error: No compatible xclbin file found.

### ISSUE THREAD

**Issue by myy1966** [amd/RyzenAI-SW#23]
I run the "Getting Started Tutorial" following the https://ryzenai.docs.amd.com/en/latest/getstartex.html. When I execute the command "python predict.py --ep ipu", there is an exception: Exception during initialization: Error: No compatible xclbin file found.
![image](https://github.com/amd/RyzenAI-SW/assets/10590090/339a517f-d78f-454d-8f26-4ca0d06a36e0)
My CPU is 7840HS. I use the ryzen-ai-sw-0.9 software package provided by https://ryzenai.docs.amd.com/en/latest/inst.html. I have set the XLNX_VART_FIRMWARE environment variable to right path. Why the onnxruntime can not find compatible xclbin?

**Comment by uday610** [comment]
Hello @myy1966 , 
I cannot think any reason it could happen unless something else going on that I cannot see. How did you set environment variable? Maybe you can double check. If you just run the installer then the environment variable is automatically set. 

`ryzen-ai-sw-0.9\ryzen-ai-sw-0.9>.\install.bat -env myrunenv
`
This will create environment and you should see message like below


```
Setting XLNX_VART_FIRMWARE env variable ...
Created conda env: myrunenv
```

Now activating conda environment and check environment variable setting by `echo %XLNX_VART_FIRMWARE%`

```
conda activate myrunenv

(myrunenv) C:\Users\Administrator\Downloads\ryzen-ai-sw-0.9\ryzen-ai-sw-0.9>
(myrunenv) C:\Users\Administrator\Downloads\ryzen-ai-sw-0.9\ryzen-ai-sw-0.9>
(myrunenv) C:\Users\Administrator\Downloads\ryzen-ai-sw-0.9\ryzen-ai-sw-0.9>echo %XLNX_VART_FIRMWARE%
C:\Users\Administrator\Downloads\ryzen-ai-sw-0.9\ryzen-ai-sw-0.9\voe-4.0-win_amd64\1x4.xclbin
```

**Comment by myy1966** [comment]
> Hello @myy1966 , I cannot think any reason it could happen unless something else going on that I cannot see. How did you set environment variable? Maybe you can double check. If you just run the installer then the environment variable is automatically set.
> 
> `ryzen-ai-sw-0.9\ryzen-ai-sw-0.9>.\install.bat -env myrunenv ` This will create environment and you should see message like below
> 
> ```
> Setting XLNX_VART_FIRMWARE env variable ...
> Created conda env: myrunenv
> ```
> 
> Now activating conda environment and check environment variable setting by `echo %XLNX_VART_FIRMWARE%`
> 
> ```
> conda activate myrunenv
> 
> (myrunenv) C:\Users\Administrator\Downloads\ryzen-ai-sw-0.9\ryzen-ai-sw-0.9>
> (myrunenv) C:\Users\Administrator\Downloads\ryzen-ai-sw-0.9\ryzen-ai-sw-0.9>
> (myrunenv) C:\Users\Administrator\Downloads\ryzen-ai-sw-0.9\ryzen-ai-sw-0.9>echo %XLNX_VART_FIRMWARE%
> C:\Users\Administrator\Downloads\ryzen-ai-sw-0.9\ryzen-ai-sw-0.9\voe-4.0-win_amd64\1x4.xclbin
> ```

Got the reason, it's due to  I ran it in Powershell. When I changed to the cmd, the example ran smoothly.
