### ISSUE TITLE
Which API would be best for accessing RyzenAI?

### ISSUE THREAD

**Issue by changtimwu** [amd/RyzenAI-SW#31]
Hi!

I need advice on the choice of AI APIs to utilize RyzenAI(AMD IPU) on Windows.  Even restricted under Windows, I found there are still quite a lot choices to access various AI acceleration hardware.

Initially, I was attracted by the ADP(Adobe Premier Pro) + RyzenAI [commercial](https://www.youtube.com/watch?v=FJHgtzhtm2w).  According to another MS [blog post](https://devblogs.microsoft.com/windowsai/dml-unlocks-new-silicon-for-adobe/), ADP's AI features are `accelerated` through `DirectML`.  Unfortunately, I soon realized that this only stands if the hardware is a GPU or Intel NPU.  `RyzenAI` doesn't offer a driver for DirectML. 

It seems this repo(RyzenAI-SW) go with the way `app -> ORT -> VitisAI EP -> RyzenAI(AMD IPU)`, which totally skips DirectML.  I still hope AMD can officially recommend the API to access RyzenAI for developers.

**Comment by ThomasXilinx** [comment]
The recommended way to access Ryzen AI is indeed to use the ONNX Runtime with the VitisAI EP. The official documentation for the Ryzen AI development flow can be found here: https://ryzenai.docs.amd.com/en/latest/
