### ISSUE TITLE
there is not Transformer model

### ISSUE THREAD

**Issue by C-L-Zhang** [amd/RyzenAI-SW#41]
when I try to run transformer example, there is no model and no image to run.
can you give some hints?

**Comment by uday610** [comment]
Hi @C-L-Zhang , if you see the top README.md file, these are examples of transformer model

[Run LLM OPT-1.3B model with ONNXRuntime](https://github.com/amd/RyzenAI-SW/blob/main/example/transformers/opt-onnx)
[Run LLM OPT-1.3B model with PyTorch](https://github.com/amd/RyzenAI-SW/blob/main/example/transformers/opt-pytorch)
[Run Vision-Transformer model with ONNXRuntime](https://github.com/amd/RyzenAI-SW/blob/main/example/transformers/vision-transformer-onnx)
 
The OPT-1.3 pretrained model will be downloaded and saved automatically from Hugging Face when you run the script as mentioned in the instructions.  

For Vision Transformer, there is no model provided as of now. You can try a Vision Transformer model (for example  [TIMM models in the Hugging Face repo](https://github.com/huggingface/pytorch-image-models) containing several Vision Transformer models). After quantization and saving the model in ONNX format, they can be used. In the later update of this example, we can add an example model or add instructions of preparing the model.

**Comment by uday610** [comment]
closed as answered
