### ISSUE TITLE
IPU not working

### ISSUE THREAD

**Issue by GiulioDeveloper** [amd/RyzenAI-SW#50]
Hello,
I have a laptop with Ryzen AI, the Lenovo Yoga Slim 7 with AMD 7840S. I wanted to test its power through Windows Studio Effects, but I noticed it was not present in my machine. I went on to check the driver for the IPU and I found that the driver is installed but the device doesn't start.
![Screenshot 2024-01-27 122747](https://github.com/amd/RyzenAI-SW/assets/32137457/85ed18ee-dc0f-4019-b8b3-11b2eb197444)
![Screenshot 2024-01-27 122803](https://github.com/amd/RyzenAI-SW/assets/32137457/1068176d-f751-4ba9-80cb-5a51df2a43ba)
![Screenshot 2024-01-27 122852](https://github.com/amd/RyzenAI-SW/assets/32137457/c366753a-80a0-4973-8e9e-c2bdecdd2881)
I also installed the Ryzen AI quicktest from the developer guide. Everything works fine, except it seems that it eventually puts the workload on the CPU instead of the IPU:
![image](https://github.com/amd/RyzenAI-SW/assets/32137457/0b6a4729-1ad4-4f51-83a5-54c72f7e8268)
I have already tried to uninstall the driver and download the one from the developer guide, and these were the results. 
I also run the xbutil executable in the driver folder and tried some commands. The device seems to be ok, it also passes the test using the xbutil validate command.

I suppose that the device is not working correctly and this is also causing Windows Effects to not show up?
Any help would be highly appreciated, thanks in advance!

**Comment by uday610** [comment]
Hi @GiulioDeveloper , as I see in your snapshot the IPU driver is properly installed, the quickest is also running the Model on the IPU. That message you highlighted just for a few nodes, and not for the whole model itself, which is running on IPU.  are just So I dont see any issue with Ryzen-AI software itself. You said Windows Studio Effect is not present which I dont understand as it is available through Windows, so can you update Windows and check? 

Thanks

**Comment by GiulioDeveloper** [comment]
Hello @uday610 , thanks for the answer. If I understood correctly, the error about the execution provider is "normal", and also the kernel error about the device not starting should not be a concern. I can tell you that the whole system is up to date (Windows and Lenovo drivers), so I don't know what's missing. I already tried with Microsoft support but with no result. If you tell me that the part concerning the IPU is alright, I can start experimenting with it and wait for Lenovo/Microsoft to solve the issue about Studio Effects drivers. 
Thanks again

**Comment by uday610** [comment]
Hi @GiulioDeveloper , there is no error about the execution provider, it is not showing as "error message", is it? Rather it is showing the message "Actually running on IPU 1" which indicates the Model subgraph is running on IPU. This looks perfectly ok to me. 

I dont know about "Event Viewer" message that you are showing, generally, I dont check it on our end. Because if the "Device Manager" is showing IPU device is working properly (I see that in your snapshot), then we generally go directly into the quickest or getting started tutorial. I will check "Event Viewer" on my end and see if I find anything.

**Comment by GiulioDeveloper** [comment]
@uday610 I assumed the three issues/warnings were connected, thanks for the explanation. Just waiting to understand if the kernel error is normal, then I will close the issue. I also hope that Microsoft/Lenovo fix the Studio Effects stuff...

**Comment by uday610** [comment]
Hi @GiulioDeveloper ,

I checked with one working laptop with IPU and saw a message like "Had a problem starting". But we can run models on IPU on this model.

![image](https://github.com/amd/RyzenAI-SW/assets/10237331/8e2d0894-d02a-4280-bee6-69b4029cd4de)

You can also run the Getting Started Tutorial Python flow, and you can also check the CPU utilization. When you run with `--ep ipu` the CPU utilization gets very low, and when we run with `--ep cpu` we see higher CPU utilization. I have a small Python "context manager" code that can be used with the inference code to show this CPU utilization, but you can also check in other ways. 

Thanks
Uday

**Comment by GiulioDeveloper** [comment]
Hi @uday610 , thanks for the confirmation. So the kernel error is not a "real problem" and I assume that missing Windows Studio Effects are Lenovo/Microsoft's drivers fault. Hope to hear from them to solve that issue. 
Thanks again and have a good day.
