### ISSUE TITLE
repository 'https://github.com/amd/RyzenAI-SW-internal.git/' not found

### ISSUE THREAD

**Issue by dannybaths** [amd/RyzenAI-SW#53]
in this section:
https://github.com/amd/RyzenAI-SW/tree/main?tab=readme-ov-file#git-lfs-and-instructions-to-clone
the command 
**git clone https://github.com/amd/RyzenAI-SW-internal.git**
gives me the following error (even after the GH authentication):

c:\BAGNID\RyzenAI>git clone https://github.com/amd/RyzenAI-SW-internal.git
Cloning into 'RyzenAI-SW-internal'...
info: please complete authentication in your browser...
**remote: Repository not found.
fatal: repository 'https://github.com/amd/RyzenAI-SW-internal.git/' not found**.

Or maybe it is just a typo error and the correct command is indeed:
git clone https://github.com/amd/RyzenAI-SW.git ?

**Comment by savitha-srinivasan** [comment]
Hi @dannybaths, 

Thank you for bringing this up. The link has now been corrected.
