### ISSUE TITLE
 node != nullptrcannot find producer

### ISSUE THREAD

**Issue by StanleyZhu51** [amd/RyzenAI-SW#63]
I am trying to run the Silero Speech-to-text model on the IPU and I am facing this issue.

![image](https://github.com/amd/RyzenAI-SW/assets/106711784/ec8a7336-c918-4cbf-b0f1-aa020dd31042)

I'm uncertain of what this means, but it is able to run just fine when I switch the execution model to CPU. I have based my code off of the Getting Started with Resnet tutorial by loading the Onnx model from this repo.

https://github.com/snakers4/silero-models

**Comment by uday610** [comment]
Hi @StanleyZhu51 , 
I am assuming you load the model like below
```
torch.hub.download_url_to_file(models.stt_models.en.latest.onnx, 'model.onnx', progress=True)
onnx_model = onnx.load('model.onnx')
```
how did you quantize the model? In the same way as resnet model of getting started tutorial? 
Thanks 
Uday

**Comment by StanleyZhu51** [comment]
Yes I tried to do it with the calibration_data_reader = None, to test if it could run at all.

```python
vai_q_onnx.quantize_static(
        input_model_path,
        output_model_path,
        calibration_data_reader=None,
        quant_format=vai_q_onnx.QuantFormat.QDQ,
        calibrate_method=vai_q_onnx.PowerOfTwoMethod.MinMSE,
        activation_type=vai_q_onnx.QuantType.QUInt8,
        weight_type=vai_q_onnx.QuantType.QInt8,
        enable_dpu=True, 
        extra_options={'ActivationSymmetric': True} 
)
```

**Comment by rhenry74** [comment]
How did this get resolved?

**Comment by yunhaolsh** [comment]
So what's causing this
