### ISSUE TITLE
AMD Ryzen™ AI Inference within a Docker container

### ISSUE THREAD

**Issue by xXxTheUserxXx** [amd/RyzenAI-SW#68]
Hello everyone,

I'm seeking guidance on how to perform inference with a quantized model inside a Docker container. I am using an AMD Ryzen™ 7 7840U and want to access the NPU from within a Docker container to infer my quantized model. If anyone knows of a guide or forum post covering this topic, I'd greatly appreciate a pointer in the right direction.

Thank you!

**Comment by uday610** [comment]
Hi, we don't have a plan to provide inference support inside from docker on Windows. You can access NPU as documented in RyzenAI documentation through the conda environment. 

Thanks
Uday

**Comment by uday610** [comment]
Closing this
