### ISSUE TITLE
Network path is not accessible for IPU drivers

### ISSUE THREAD

**Issue by nim5211** [amd/RyzenAI-SW#69]
Hello Team,

I am working on to implement Llama2 on AMD Ryzen laptop. However, I am facing an error as " Path not found" for the shared network drive.

Can you help me to download IPU drivers, so that I can able to run the demo.

Thanks,

**Comment by uday610** [comment]
Hi
You should be able to download NPU driver from the link of this page: https://ryzenai.docs.amd.com/en/latest/inst.html#prepare-the-system
