### ISSUE TITLE
ModuleNotFoundError: No module named 'qlinear'

### ISSUE THREAD

**Issue by fengzhaoxin** [amd/RyzenAI-SW#72]
I am trying the Transformers examples following the "Setup Transformers" and "Llama 2 - Pytorch" instructions step by step. However, an error occurred, which is as follow:
```
python run_awq.py --w_bit 4 --task quantize
Traceback (most recent call last):
  File "C:\Users\zxfeng\Documents\AI_Proj\RyzenAI-SW\example\transformers\models\llama2\run_awq.py", line 14, in <module>
    import qlinear
ModuleNotFoundError: No module named 'qlinear'
```
Is there any solution for this problem? Looking forward to your reply soon.
![image](https://github.com/amd/RyzenAI-SW/assets/57025930/4a72811f-a214-4699-90f0-b06f9b4bbc75)

**Comment by nim5211** [comment]
Hello, I am  also facing same problem and not able to find a way to install qlinear. can you guys help us in resolving the issue?

**Comment by fengzhaoxin** [comment]
> Hello, I am also facing same problem and not able to find a way to install qlinear. can you guys help us in resolving the issue?

hi, my problem is because I didn't install RyzenAI packets successfully which is in the "Step 3: Build dependencies
pip install ops\cpp --force-reinstall". you should go through step2 and step3 again.(If there is a RyzenAI packets in your python environment, you should uninstall it first)
Most importantly, you should run all the command in CMD environment. DO NOT USE WINDOWS TERMINAL!!!
Hope this can help you!

**Comment by 1771801582** [comment]
> > Hello, I am also facing same problem and not able to find a way to install qlinear. can you guys help us in resolving the issue?
> 
> hi, my problem is because I didn't install RyzenAI packets successfully which is in the "Step 3: Build dependencies pip install ops\cpp --force-reinstall". you should go through step2 and step3 again.(If there is a RyzenAI packets in your python environment, you should uninstall it first) Most importantly, you should run all the command in CMD environment. DO NOT USE WINDOWS TERMINAL!!! Hope this can help you!

@fengzhaoxin Anaconda Prompt works?
