### ISSUE TITLE
does amd have neural speed equivalent repo?

### ISSUE THREAD

**Issue by kolinfluence** [amd/RyzenAI-SW#73]
e.g.
https://github.com/intel/neural-speed

**Comment by uday610** [comment]
The repo you showed seems to be CPU-specific. This RyzenAI-SW is currently specific to NPU. We do not have any other repo specific to NPU.

**Comment by uday610** [comment]
You can find running LLMs on NPU, such as LLAMA and OPT, in the top-level README. We have a plan to add more LLM examples/scripts in the coming weeks/months. 

Thanks
