### ISSUE TITLE
Error when apply 4x4.xclbin

### ISSUE THREAD

**Issue by ngdymx** [amd/RyzenAI-SW#78]
Hi team,

I select the Latency Profile, and set the requirement shown in the tutorial. However,  when I ran 'python quickest.py', I encountered the error shown in the following figure.
<img width="655" alt="image" src="https://github.com/amd/RyzenAI-SW/assets/58451250/43b69b8e-3c0d-42fd-92b8-fabe228aa362">
<img width="1884" alt="image" src="https://github.com/amd/RyzenAI-SW/assets/58451250/a97686b5-91b9-44c2-81e5-d9fab148ca16">
Could you help me with it, and teach me how to use 4x4.xclbin? Thanks a lot!

**Comment by uday610** [comment]
Can you delete the "cache folder" and rerun it? I think there should be a folder named `modelcachekey_quick` that is being generated. Please try after deleting that folder.

**Comment by ngdxzy** [comment]
Hi,

It works, thanks a lot!

By the way, can I ask that do I need to delete the `modelcachekey_quick` every time if I want to change the `.xclbin` file?

**Comment by uday610** [comment]
Yes, because we need to recompile for every XCLBIN. The compiled model is saved inside the cache, so if you change the XCLBIN, it tries to use the compiled model from the saved cache, and hence, you get this error. 

In the quicktest.py, line number 16 specifies the cache folder.

```
'cacheKey': 'modelcachekey_quick'
```

If you don't specify the cache folder like the quicktest code, the default cache folder will be `C:\temp\{user}\vaip\.cache`

**Comment by ngdymx** [comment]
Hi,

I see, thank you very much! I also see some other `.xclbin` file under the` \voe-4.0-win_amd64` dictionary, like `aieml_gemm_asr.xclbin`.  What's kind of condition should I use 
them?  Is there any difference between them?

Sorry, it is my first time to access it, so I have a lot of questions.

**Comment by uday610** [comment]
1x1 and 4x4 XCLBINs are mainly used for CNN models. 

The repo contains some LLM examples that use different XCLBINs. The examples' setups pick the right XCLBIN for their purpose. XCLBIN `aieml_gemm_asr.xclbin` is only for a specific ASR model.

**Comment by ngdymx** [comment]
Hi,

I see, thanks a lot
