### ISSUE TITLE
Issue with OPT-ONNX Transformer Example

### ISSUE THREAD

**Issue by pyuvaraj37** [amd/RyzenAI-SW#83]
Hello, 

I am having issues running the OPT transformer example in the ONNX quantization flow. All the steps for setup are completed without issue, and the quantized model is run on the CPU successfully; however, when running with AIE flag for the NPU the program crashes during the warm-up stage of run.py:

![opt-onnx-error](https://github.com/amd/RyzenAI-SW/assets/44195809/2e1e8753-e31a-41bf-9e81-53331d48858b)

I am running on the Minis Forum U790 Pro Venus series provided by Hackster and AMD for the Pervasive AI Developer Contest. I have discussed the issue with other's in the Hackster discord and a few others seems to be running into the same issue. The results can be reproduced by following the transformer example. The OPT example using the PyTorch quantization flow seems to work, and I will try that for my custom model. 

Thank you!

**Comment by jens-ajisai** [comment]
> The OPT example using the PyTorch quantization flow seems to work, and I will try that for my custom model.
Do you run the OPT example using PyTorch as described and see NPU utilization for the PyTorch flow? For me it works but without NPU.

**Comment by uday610** [comment]
Hi @pyuvaraj37 ,
We have seen this issue recently. We need to do an update to fix this issue with OPT-ONNX. 
You can run OPT PyTorch flow, which works correctly.

**Comment by pyuvaraj37** [comment]
Thank you. Yes I was able to use the PyTorch flow with my own transformer as well.

**Comment by uday610** [comment]
Good to know, closing this issue
