### ISSUE TITLE
ImportError: DLL load failed while importing RyzenAI: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by Student-WangZhengTao** [amd/RyzenAI-SW#84]
(ryzen) C:\RyzenAI-SW-main\example\transformers\models\llama2>python run_awq.py --w_bit 4 --task quantize
Traceback (most recent call last):
  File "C:\RyzenAI-SW-main\example\transformers\models\llama2\run_awq.py", line 14, in <module>
    import qlinear
  File "C:\RyzenAI-SW-main\example\transformers\ops\python\qlinear.py", line 21, in <module>
    import RyzenAI
ImportError: DLL load failed while importing RyzenAI: %1 不是有效的 Win32 应用程序。

**Comment by Student-WangZhengTao** [comment]
I am having issues running the llama2 in the AWQ quantization flow. Can you help me? Thank you.

**Comment by Student-WangZhengTao** [comment]
![0d216c939a83de68dc83cba30aa62bb](https://github.com/amd/RyzenAI-SW/assets/139683988/d4571c59-94ed-4638-9e2f-d10004253225)

**Comment by poganesh** [comment]
Could you please try doing a fresh clone of the repository and setting up a new conda environment to see if that resolves the problem? 

If you still face the issue, it would be helpful if you could provide the system information - OS name/version, System Architecture - 32-bit or 64-bit, System Model, Processor so we can better assist you. Thanks.

**Comment by ksjogo** [comment]
@Student-WangZhengTao what was your solution here?
