### ISSUE TITLE
will ryzen ai will running under Ubuntu?

### ISSUE THREAD

**Issue by joebnb** [amd/RyzenAI-SW#87]
hi，i'm a developer using AMD cpu，and i want know did ryzenAi support Linux ，seems official site documented only support win11

<img width="1174" alt="image" src="https://github.com/amd/RyzenAI-SW/assets/1646883/7fc5228b-8013-4067-9b1d-23efd6ecbccb">

and if it works well will it work well under virtio environments like PVE？

**Comment by joebnb** [comment]
i see
![image](https://github.com/amd/RyzenAI-SW/assets/1646883/dd257695-182a-416c-a553-3af7a20e3877)

it's works on ubuntu，but not sure did it will work on pve environment

**Comment by grigio** [comment]
I think it's a dup of #2
