### ISSUE TITLE
YoloV10 on Ryzen

### ISSUE THREAD

**Issue by mht-sharma** [amd/RyzenAI-SW#91]
## Description

I was trying to run the Yolov10 model on Ryzen. I quantized the ONNX model using the VitisAI ONNX Quantizer. I used the following configuration as per the [VitisAI ONNX Quantizer documentation](https://ryzenai.docs.amd.com/en/latest/vai_quant/vai_q_onnx.html#cnns-on-npu).

To my surprise, only 2% of the operators ran on the DPU. Upon checking the Vitisai_ep_report.json file, I found that the Conv was running on the CPU instead of the DPU.

![image](https://github.com/amd/RyzenAI-SW/assets/21088122/02cdb26c-6f1e-419a-9f4a-77755df24634)

### Models
You can find the quantized models and other artifacts here: [Yolov10s model](https://huggingface.co/mohitsha/yolov10s/tree/main)

Note: I wanted to check only if the model runs on Ryzen and not worry about accuracy, hence the model is not quantized with accuracy in mind.

### Expected Behavior

- The Conv operator should run on the DPU for better performance.

Any help or insights into resolving this issue would be greatly appreciated.

@uday610

**Comment by uday610** [comment]
Hi @mht-sharma , looking into this

**Comment by uday610** [comment]
Hi @mht-sharma , currently yolov10 model is not supported.

**Comment by uday610** [comment]
closing it
