### ISSUE TITLE
Demo consultation

### ISSUE THREAD

**Issue by huzi-12** [amd/RyzenAI-SW#96]
The demo shows LLama2 and OPT models. Do other LLM models support it?
What is the maximum supported model parameter size? Is 13B supported? thank you

**Comment by uday610** [comment]
Yes, some other LLM can be run similar to llama2 or OPT PyTorch flow. We will release flow/script to run more models soon.

**Comment by ksjogo** [comment]
@uday610 do you have a timeline for that? And are you running them from a fresh install?

**Comment by uday610** [comment]
Yes they will be available with Ryzen AI 1.2 release should be in a month or so.
