### ISSUE TITLE
AMD IPU error code 10 in windows KVM machine

### ISSUE THREAD

**Issue by HaoyunJi** [amd/RyzenAI-SW#97]
Hello
I purchased an AMD 8845 HS processor computer (GMK K8). 

The PVE virtualization system is installed, the IPU in the host BIOS has been turned on, and the IPU can be seen in the PVE, and then I have passed the IPU PCI device directly to the Win11 virtual machine. 
![image](https://github.com/amd/RyzenAI-SW/assets/57861564/73ecc8ee-905a-43d3-a9ac-0f6a32e7c878)

The IPU device is also available in the win11 virtual machine, although the ipu driver has been followed in the virtual machine, but he keeps showing that the device cannot be started. (Code 10). 
![image](https://github.com/amd/RyzenAI-SW/assets/57861564/3e210657-aaf8-47f3-bb35-5588658f64eb)

At the same time, I can see the error code 0xC00000E5 in the event
```txt
There is a issue with device PCIVEN_1022&DEV_1502&SUBSYS_15021022&REV_003&267a616a&0&88 on startup.

Driver name: oem31.inf
Class GUID: {4d36e97d-e325-11ce-bfc1-08002be10318}
Service: kipudrv
Low-level screening procedure: 
High-level screening procedure: 
Problem: 0x0
Status: 0xC00000E5
```

Any idea?

**Comment by uday610** [comment]
Virtualization is not supported

**Comment by joebnb** [comment]
is there any update no this?

**Comment by xuhuigithub** [comment]
插眼
