### ISSUE TITLE
Clarification on AIE and CPU Performance Comparison for Llama2

### ISSUE THREAD

**Issue by jtanisha** [amd/RyzenAI-SW#98]
Hello, I have questions about the term "AIE" and its performance implications in the provided Llama2 code. Could you explain what "AIE" refers to—whether it's a specific type of hardware or architecture? Additionally, how does running the model on AIE compare to running it on a CPU in terms of latency and throughput, and are there specific scenarios where AIE has significant advantages? 
Thanks for your assistance!

**Comment by uday610** [comment]
AIE (now referred as NPU) is dedicated hardware where AI tasks can be offloaded, improving performance and lowering power. https://ryzenai.docs.amd.com/en/latest/
